### PR TITLE
Add support for Fedora

### PR DESCRIPTION
**Pull request by chapmanjacobd**
this folder contains i386 folder etc

### CODE REVIEW

**Comment by snyball** [comment]
Sorry for the late response, the directory is called `xdg`, but it contains console keymaps right? If so, then I can merge this right away.

**Comment by chapmanjacobd** [comment]
yeah it looks like this:

```sh
🃈 ls -lah /lib/kbd/keymaps/legacy/
Permissions Size User Date Modified Name
drwxr-xr-x@    - root  4 May  2:25  amiga/
drwxr-xr-x@    - root  4 May  2:25  atari/
drwxr-xr-x@    - root 10 Feb 17:26  i386/
drwxr-xr-x@    - root  4 May  2:25  include/
drwxr-xr-x@    - root 10 Feb 17:26  mac/
drwxr-xr-x@    - root  4 May  2:25  sun/
lrwxrwxrwx@    3 root 10 Feb 17:26  ppc -> mac
🃃 ls -lah /lib/kbd/keymaps/xkb/
Permissions Size User Date Modified Name
.rw-r--r--@ 3.8k root 10 Feb 17:26  al-plisi.map.gz
.rw-r--r--@ 4.1k root 10 Feb 17:28  al.map.gz
.rw-r--r--@ 4.0k root 10 Feb 17:26  at-mac.map.gz
.rw-r--r--@ 3.9k root 10 Feb 17:26  at-nodeadkeys.map.gz
.rw-r--r--@ 3.9k root 10 Feb 17:26  at-sundeadkeys.map.gz
.rw-r--r--@ 3.9k root 10 Feb 17:28  at.map.gz
.rw-r--r--@ 3.4k root 10 Feb 17:28  az.map.gz
.rw-r--r--@ 4.1k root 10 Feb 17:26  ba-alternatequotes.map.gz
.rw-r--r--@ 4.0k root 10 Feb 17:26  ba-unicode.map.gz
.rw-r--r--@ 4.0k root 10 Feb 17:26  ba-unicodeus.map.gz
.rw-r--r--@ 4.1k root 10 Feb 17:26  ba-us.map.gz
.rw-r--r--@ 4.1k root 10 Feb 17:28  ba.map.gz
.rw-r--r--@ 4.0k root 10 Feb 17:26  be-iso-alternate.map.gz
.rw-r--r--@ 4.0k root 10 Feb 17:26  be-nodeadkeys.map.gz
.rw-r--r--@ 4.2k root 10 Feb 17:26  be-oss.map.gz
```

**Comment by snyball** [comment]
Nice, then I'll merge.

**Comment by snyball** [comment]
Crap, it should be merged into master, the `-develop` branch has been unused for a long time.

Do you want to make a new pull request on `master`, or do you only use the older `-develop` branch?

**Pull request merged**
