### PR TITLE
Add user-configurable paths

### PR DESCRIPTION
**Pull request by lgbaldoni**

### CODE REVIEW

**Comment by snyball** [comment]
Have you tested this with different locations for `HAWCK_SHARE`, `HAWCK_CFG`,
etc? I'm not 100% sure but I think the C++ code has some hardcoded assumptions
that need to be modified before this can be merged. I'll have to check that
first.

I also don't see the `meson.build` configuration for generating the output
files. E.g:

``` meson
configure_file(
  input: 'hawck-install.sh.in',
  output: 'hawck-install.sh',
  install_dir: ...,
  configuration: ...
)
```

**Comment by lgbaldoni** [comment]
> Have you tested this with different locations for HAWCK_SHARE, HAWCK_CFG,
etc? I'm not 100% sure but I think the C++ code has some hardcoded assumptions
that need to be modified before this can be merged. I'll have to check that
first.

To be honest no, I haven't checked it at all beyond it building both with hardcoded paths and openSUSE defaults.
I had assumed the code always relied on ~/.local for the actual configuration files.

> I also don't see the meson.build configuration for generating the output
files. 

Silly me, forgot to add those to the commit. They are there now.

**Comment by snyball** [comment]
I'm going to try out the Arch PKGBUILD on your fork, then do some grepping for hardcoded paths in the code. After I've confirmed that the PKGBUILD works, and that there are no hardcoded paths to change then we can merge this.

If I find any hardcoded paths then they should be modified by this pull request, so I'll post them here if I find them.

**Comment by snyball** [comment]
The PKGBUILD works and I'm getting the exact same output for `hawck-user-setup` as before, so I'm going to merge it now.

PS: You'll also need `post_install` from https://aur.archlinux.org/cgit/aur.git/tree/hawck-git.install?h=hawck-git when packaging, it's kept as a submodule in `bin/hawck-git/` and is executed by `install.sh`.

**Comment by lgbaldoni** [comment]
> PS: You'll also need post_install from https://aur.archlinux.org/cgit/aur.git/tree/hawck-git.install?h=hawck-git when packaging, it's kept as a submodule in bin/hawck-git/ and is executed by install.sh

Right, forgot about that one.
But in rpm one needs to do that by hand in %pre/%post/%preun/%postun. Can I just ignore it and implement it differently?

**Comment by snyball** [comment]
@lgbaldoni Of course, as long as you make sure everything in `post_install` happens somehow then it should work the same.

**Pull request merged**
